### PR TITLE
Fix Mini Pets

### LINKED ISSUE #239: Murloc pets should dance.
**Current behavior**: 
They are not dancing.

**Expected behavior**: 
The four murloc pets summoned by these items (https://classic.wowhead.com/search?q=murloc+egg) should be dancing when they are summoned. I have done some research and seems like they should have this aura: https://classic.wowhead.com/spell=24983/baby-murloc-passive that will trigger https://classic.wowhead.com/spell=24984/baby-murloc every 15 minutes, that last spell is a 15 seconds channel that will play baby murloc sounds, but the dance behavior needs to be scripted server-side. I think the emote shouldn't be "one shot", it should play even if moving, but they must stop dancing after 15 seconds, when the channeled spell ends.

P.S.: This is db-related, but these creatures are missing in the database: https://classic.wowhead.com/search?q=baby+murloc

### PR DESCRIPTION
**Pull request by Oroxzy**
**Fixed some values and let them use their auras.**
88641-mini-diablo

fixes #239 

**Proof:**
use this query on mass parse db with an existing vmangos world db named "mangos"
```sql
SELECT
    spell_template.entry AS spell_entry,
    spell_template.name AS spell_name,
    creature_template.entry,
    creature_template2.name AS creature_name,
	creature_template.auras,
	CAST(IFNULL(creature_template.auras, 0) AS int),
	CAST(IFNULL(creature_template2.auras, 0) AS int),
    CONCAT('UPDATE `creature_template` SET ',
    IF ((CAST(IFNULL(creature_template.auras, 0) AS int) = CAST(IFNULL(creature_template2.auras, 0) AS int)), '', CONCAT('`auras`=', IFNULL(creature_template.auras, 0))),
    IF ((creature_template.unit_flags = creature_template2.unit_flags), '', CONCAT(', `unit_flags`=', creature_template.unit_flags)),
    IF ((creature_template.speed_walk = creature_template2.speed_walk), '', CONCAT(', `speed_walk`=', creature_template.speed_walk)),
    IF ((creature_template.speed_run = creature_template2.speed_run), '', CONCAT(', `speed_run`=', creature_template.speed_run)),
    IF ((creature_template.base_attack_time = creature_template2.base_attack_time), '', CONCAT(', `base_attack_time`=', creature_template.base_attack_time)),
    IF ((creature_template.ranged_attack_time = creature_template2.ranged_attack_time), '', CONCAT(', `ranged_attack_time`=', creature_template.ranged_attack_time)),
    IF ((creature_template.faction = creature_template2.faction), '', CONCAT(', `faction`=', creature_template.faction)),
    ' WHERE `entry`=', creature_template.entry, ';') AS query
FROM creature_template
JOIN mangos.spell_template ON creature_template.entry = mangos.spell_template.effectMiscValue1
JOIN mangos.creature_template AS creature_template2 ON creature_template.entry = creature_template2.entry
WHERE
    creature_template.entry IN (SELECT effectMiscValue1 FROM mangos.spell_template WHERE effect1 = 97 OR effect2 = 97 OR effect3 = 97 GROUP BY effectMiscValue1) AND (
    NOT creature_template.speed_walk = creature_template2.speed_walk OR
    NOT creature_template.speed_run = creature_template2.speed_run OR
    NOT creature_template.faction = creature_template2.faction OR
    NOT creature_template.base_attack_time = creature_template2.base_attack_time OR
    NOT creature_template.ranged_attack_time = creature_template2.ranged_attack_time OR
    NOT creature_template.unit_flags = creature_template2.unit_flags OR
    NOT CAST(IFNULL(creature_template.auras, 0) AS int) = CAST(IFNULL(creature_template2.auras, 0) AS int)) AND (
    spell_template.effect1 = 97 OR
    spell_template.effect1 = 97 OR
    spell_template.effect1 = 97 )
```

### CODE REVIEW

File: src/game/Objects/Pet.cpp [hunk 1]
```diff
@@ -2287,9 +2288,22 @@ bool Pet::Create(uint32 guidlow, CreatureCreatePos& cPos, CreatureInfo const* ci
     SetSheath(SHEATH_STATE_MELEE);
     SetByteValue(UNIT_FIELD_BYTES_2, UNIT_BYTES_2_OFFSET_MISC_FLAGS, UNIT_BYTE2_FLAG_UNK3 | UNIT_BYTE2_FLAG_AURAS | UNIT_BYTE2_FLAG_UNK5);
 
-    if (getPetType() == MINI_PET)                           // always non-attackable
-        SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER | UNIT_FLAG_IMMUNE_TO_NPC);
+    if (getPetType() == MINI_PET)
+    {
+        SetFlag(UNIT_FIELD_FLAGS, UNIT_FLAG_IMMUNE_TO_PLAYER | UNIT_FLAG_IMMUNE_TO_NPC); // always non-attackable
 
+        CreatureInfo const* normalInfo = ObjectMgr::GetCreatureTemplate(this->GetEntry());
```
Comment (ratkosrb) [inline src/game/Objects/Pet.cpp]: you are given the cinfo as parameter, why are you looking it up

**Comment by ratkosrb** [comment]
Why are you updating the ranged attack time? This is not even a sniffable value.

**Comment by ratkosrb** [comment]
And the unit flags are assigned by core for mini pets, why do u set them in db too? Do these entries actually have the Immune to PC/NPC static flags in their creature difficulty record (blizzard's equivalent of template) ?

**Comment by ratkosrb** [comment]
And what about the faction update, aren't mini pets always their owner's faction? I only checked 9657, but in sniffs its the player's faction, not 35, and in creature difficulty its 188, so where is the update to 35 coming from?

File: src/game/Objects/Pet.cpp [hunk 2]
```diff
@@ -20,6 +20,7 @@
  */
 
 #include "Pet.h"
+#include "Creature.h"
```
Comment (ratkosrb) [inline src/game/Objects/Pet.cpp]: Pet.h already includes Creature.h, since Pet inherits from Creature.
