### PR TITLE
Correct Ironforge Mountain spawns.

### LINKED ISSUE #3155: 🐛 [Bug] Missing Coldmine Explorer / Seasoned Coldmine Explorer Spawns
## 🐛 Bug report
There are 3 missing spawns 2 are seen here
https://youtu.be/LhOA3mzW40E?t=531

1 paths from the cave  at x -4603.5 y -815.47 z 639.62

### PR DESCRIPTION
**Pull request by Daribon**
## 🍰 Pullrequest

This PR updates adds 5 missing spawns on the Ironforge Mountain and corrects waypoints for almost all NPCs in Ironforge Airport. 

Previous waypoints were based on cmangos and was about 1/3 - 2/3 sniffed at times. PR makes waypoints fully based on sniff.

Do note that this doesn't fix the custom troll mess in the south of Ironforge Airport, I have it sniffed but will parse it and PR it at later point. In the current PR I've only cleaned up the worst offender troll spawns.

### Proof

- My own sniff, ironforge_airport_mountain_1.13.6.36714

### Issues

- Fixes https://github.com/vmangos/core/issues/3155

### How2Test

- .go creature any of the guids in the SQL.

### Todo / Checklist

- [ ] Prevent AV script from running outside AV for Coldridge explorer and Seasoned Coldmine Explorer.
- [X] Figure out why guid 190209 keeps using crafting emote. (When found, craft emote should be deleted and it  should only have crying emote.)

### CODE REVIEW

File: sql/migrations/20251209233625_world.sql [hunk 1]
```diff
@@ -0,0 +1,475 @@
...
+-- Delete duplicate rabbit
+DELETE FROM creature WHERE `guid`=190186;
+
+-- Correct emote for Ironforge Mountainer
+UPDATE `creature_addon` SET `emote_state`=28 WHERE `guid`=190201;
+
+-- Emote 69 for Ironforge Guard
+DELETE FROM `creature_movement` WHERE `id`=190209;
+DELETE FROM `creature_movement_scripts` WHERE `id`=21;
+INSERT INTO `creature_addon` (`guid`,`emote_state`) VALUES (190209, 69);
```
Comment (ratkosrb) [inline sql/migrations/20251209233625_world.sql]: you added the crafting emote here, while the crying emote comes from EventAI

**Comment by ratkosrb** [comment]
image

**Comment by ratkosrb** [comment]
got some errors in console when i went to the airstrip
image

**Comment by Daribon** [comment]
Fixed the previous issues. All that remains now is: Prevent AV script from running outside AV for Coldridge explorer and Seasoned Coldmine Explorer.

Do note, there will be another PR at later point to fix the south area of Ironforge Airport once I'm able to parse it.
