### PR TITLE
Misc DB Fixes

### LINKED ISSUE #2085: 🐝 [Bug] Quest Darkmoon Beast Deck incorrect quest text.
## 🐝 Bug report - Quest

The quest Darkmoon Beast Deck currently has incorrect quest text.
It incorrectly uses the quest text from Brann Bronzebeard's Lost Letter.
heidisql_7s1fvZwgzY

The quest OfferReward and RequestItems text is not sniffed.

### Expected behavior

It should have the following text according to wowhead:

RequestItems:

- I see that you have managed to complete a deck of beasts!   Congratulations!

OfferReward:

- So you have put together a deck of Beasts.   Your gesture of returning it to us will create a tie between you and the Darkmoon that will not soon be forgotten.   Allow me to present you with one of the greater darkmoon cards as a small token of our appreciation.

### Steps to reproduce

1. .additem 19228
2. Click on the item and accept the quest.
3. .npc spawn add 14847
4. Turn in the quest.
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/026ac142e41e22cd693c2e33684e5863493e69f1

OS Client: Windows 11 Pro N 10.0.22621.1413
OS Server: Windows 11 Pro N 10.0.22621.1413

### Crashlog

- None

### LINKED ISSUE #2101: 🐝 [Bug] Quest Elixir of Pain wrong creature XP multiplier
## 🐝 Bug report - Quest
After you complete Quest 502 Elixir of Pain you feed the elixir to Stanley which morphs to Enraged Stanley and the creature give you 1 time the base XP_multiplier

### Expected behavior
Enraged Stanley should give you 10 times the base XP_multiplier upon death

### Steps to reproduce
1. .quest add 502
2. feed the elixir to Stanley
3. kill Enraged Stanley

Commit Hash:  
2ed34467bcde8a0702981d9d212e49000bda7cdc
  - Win 10

### LINKED ISSUE #2115: 🐛 [Bug] Wrong spawn point causes mobs to evade constantly
## 🐛 Bug report

Dabyrie Laborer and Drywhisker Digger evades all attacks because wrong spawn point, both are found in Arathi Higlands
### Expected behavior

They should aggro and move correctly
### Steps to reproduce

1. .go creature 11352 or 13252
2. aggro and watch them evade

### Version & Environment

Client Version: 
  - 1.12.1.5875
<!--

### LINKED ISSUE #2395: 🐝 [Bug] Quest: Root Samples (866)
## 🐝 Bug report - Quest
Item Root Sample (5056) cannot be gathered from herbs in the Barrens.

Previous to the mass herb updates all of the herbs in the Barrens where using the wrong object id's for example Peacbloom's use object 1618 everywhere apart for the Barrens where they use object id 3724. All of the loot tables must now be swapped for:

- [ ] Briarthorn 1621 <-> 3729

- [ ] Bruisweed 1622 <-> 3730

- [ ] Earthroot 1619 <-> 3726

- [ ] Mageroyal 1620 <-> 3727

- [ ] Peacebloom 1618 <-> 3724

Commit Hash: 312da6a

### LINKED ISSUE #2404: 🐛 [Bug] Swiftthistle not harvesting from Barrens
Players have reported that swiftthistle is currently not being harvested from barrens herb nodes (it is a tertiary drop from other herb spawns)
Possibly related to some of the ID reworks done here:
https://github.com/vmangos/core/issues/2395#issuecomment-1874277747

### LINKED ISSUE #2655: 🦂 [Bug]LBRS - Flame Buffet totem wrong spell ID
## 🦂 Bug report - Dungeon
The Flame Buffet Totem's(cast by Smolderthorn Witch Doctor) Flame Buffet spell has the wrong spell ID

### Expected behavior
https://www.wowhead.com/classic/npc=9266/smolderthorn-witch-doctor their totem - > 
https://www.wowhead.com/classic/npc=10217/flame-buffet-totem wrong spell id
https://www.wowhead.com/classic/spell=16168/flame-buffet - current one (deals 800 damage)
https://www.wowhead.com/classic/spell=9574/flame-buffet - correct one
https://youtu.be/qUeh_vws5YE?t=1125

I don't know how to commit sql fixes
```

UPDATE `mangos`.`creature_template` SET `spell_id1`=9574 WHERE  `entry`=10217 AND `patch`=0;
UPDATE `mangos`.`creature_template` SET `spell_id1`=9574 WHERE  `entry`=10217 AND `patch`=10;
```

### Version & Environment

Client Version:  1.12.1

### LINKED ISSUE #2669: 🐝 [Bug]The Treasure of the Shen'dralar can accept quest twice
## 🐝 Bug report - Quest
Can accept The Treasure of the Shen'dralar twice. 

### Expected behavior
Should only be able to accept it once.

image

image (2)

### LINKED ISSUE #2670: 🐛 [Bug]Twilight Flamereaver wrong immolate spell Id
## 🐛 Bug report
Twilight Flamereaver have the wrong spell ID
They are using https://www.wowhead.com/classic/spell=9276/immolate

### Expected behavior
Correct one:
https://www.wowhead.com/classic/npc=15201/twilight-flamereaver#abilities
https://www.wowhead.com/classic/spell=15732/immolate

### LINKED ISSUE #2790: 🐛 [Bug] Silithid Hive Drone (4133) call for help
## 🐛 Bug report

If attacking a Silithid Hive Drone it pulls too many mobs:
https://github.com/user-attachments/assets/76de524e-4df2-494c-99f3-d1f06b6c726b

### Expected behavior

**Edit: Removed video from private server and added two others**

According to these videos from [wowhead classic](https://www.wowhead.com/classic/quest=1147/the-swarm-grows) there should be far fewer adds:
https://www.youtube.com/watch?v=rxutea44ack
https://www.youtube.com/watch?v=P5A3sGrVj4o

Perhaps someone can verify this.

### Steps to reproduce

1. `.go -6361.11 -3555.94 -58.5096 1`
2. attack drones

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  e56fce5e65e254a01af938747cebfc30d7d6ac1b

OS Client: Ubuntu 24.04 (Wine)
OS Server: Ubuntu 22.04

### Crashlog

- None

### LINKED ISSUE #2804: 🐛 [Bug]No Swiftthistle herbed at all from Briarthorn and Mageroyal in The Barrens only (works in other places).(duplicate)
## 🐛 Bug report

https://www.wowhead.com/classic/item=2452/swiftthistle#gathered-from-object
Swiftthistle should be able to be gathered from Briarthorn and Mageroyal in The Barrens but after herbing many stacks of each over the course of more than a week, by 3 different herbalists, never did any Swiffthistle appear. It looks to be OK outside of The Barrens.
### Expected behavior

1-2 Swiffthistle should drop from Briarthorn and Mageroyal in The Barrens with resp. 39% and 20% chance.
Also: Briarthorn should give 1-3 pieces and I got 2 pieces every time. Same for Mageroyal.
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 
  - 1.12.1.5875

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

### PR DESCRIPTION
**Pull request by NickTyrer**
## 🍰 Pullrequest
closes https://github.com/vmangos/core/issues/2115
closes https://github.com/vmangos/core/issues/2395
closes https://github.com/vmangos/core/issues/2404
closes https://github.com/vmangos/core/issues/2804
closes https://github.com/vmangos/core/issues/2669
closes https://github.com/vmangos/core/issues/2670
closes https://github.com/vmangos/core/issues/2790
closes https://github.com/vmangos/core/issues/2655
closes https://github.com/vmangos/core/issues/2879
closes https://github.com/vmangos/core/issues/2970
closes https://github.com/vmangos/core/issues/2101
closes https://github.com/vmangos/core/issues/2085
closes https://github.com/vmangos/core/issues/2815

### CODE REVIEW

File: sql/migrations/20241208211202_world.sql [hunk 1]
```diff
@@ -883,7 +883,26 @@ INSERT INTO `creature` (`guid`, `id`, `id2`, `id3`, `id4`, `id5`, `map`, `positi
...
+(3224, 12123, 0, 0, 0, 0, 1, 3573.60009765625000000000, 1690.84997558593750000000, -69.00000000000000000000, 1.89300000667572020000, 300, 900, 20, 100, 0, 1, 0, 0, 0, 10),
+(3239, 12123, 0, 0, 0, 0, 1, 3598.22998046875000000000, 1496.96997070312500000000, -59.00000000000000000000, 2.94700002670288100000, 300, 900, 20, 100, 0, 1, 0, 0, 0, 10),
+(3243, 12123, 0, 0, 0, 0, 1, 3934.91992187500000000000, 2020.13000488281250000000, -82.00000000000000000000, 2.90799999237060550000, 300, 900, 20, 100, 0, 1, 0, 0, 0, 10),
+(3246, 12123, 0, 0, 0, 0, 1, 4371.18994140625000000000, 1238.92004394531250000000, -52.00000000000000000000, 2.54800009727478030000, 300, 900, 20, 100, 0, 1, 0, 0, 0, 10),
+(3248, 12123, 0, 0, 0, 0, 1, 4162.35986328125000000000, 1611.14001464843750000000, -57.70479965209961000000, 6.23635005950927700000, 300, 900, 20, 100, 0, 1, 0, 0, 0, 10),
+(3255, 12123, 0, 0, 0, 0, 1, 3725.20991210937500000000, 2096.93994140625000000000, -79.31400299072266000000, 3.44137001037597660000, 300, 900, 20, 100, 0, 1, 0, 0, 0, 10);
```
Comment (ratkosrb) [inline sql/migrations/20241208211202_world.sql]: Where are the waypoints? They are all supposed to have waypoints. You can see on classic they travel really long paths, they are not wandering in 20 yard radius.

Comment (NickTyrer) [reply sql/migrations/20241208211202_world.sql]: I have the correct data now. Will update soon.

File: sql/migrations/20241208211202_world.sql [hunk 2]
```diff
@@ -0,0 +1,622 @@
...
+(847901, 9, 0, 1, 18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 'Kalaran Windblade - Emote');
+-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
+-- Add Correct Gossip to Joseph Redpath (NOTE: currently his gossip is controlled by a cpp script that only displays the placeholder gossip. If the script is converted to DB in the future this correct gossip menu will be used.)
+UPDATE `creature_template` SET `gossip_menu_id` = 3861 WHERE `entry` = 10936;
+INSERT INTO `gossip_menu` VALUES
+(3861, 4778, 0, 0);
+UPDATE `creature` SET `wander_distance` = 1.5, `movement_type` = 1 WHERE `guid` = 53736;
+-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
+-- Update Creature Flags
+UPDATE `creature_template` SET `static_flags1` = 4718598 WHERE `entry` = 6237;
```
Comment (ratkosrb) [inline sql/migrations/20241208211202_world.sql]: This contradicts WDB data from original vanilla. This npc should be Sessile. You will also notice that in all classic sniffs parses it has wander_distance = 0 meaning it has never been seen moving.
