### PR TITLE
Fix patch for graveyards.

### LINKED ISSUE #1492: 🐜 [Bug][1.7.1]Player will be revived on Gurabashi arena after they died in dungeon Uldaman
## 🐜 Bug report - Progression

When player dead in Uldaman, they should be revived on Badlands, not Gurabashi arena, this issue only happen on old patch of server like 1.7.1.
### Steps to reproduce

1. `.tele uldaman`
2. `.die` to kill yourself and press release spirit

### Version & Environment

Client Version: 1.7.1.4695

Commit Hash:  

OS Client: Windows 10
OS Server: Windows server 2008 R2

### Crashlog

- None

### LINKED ISSUE #1590: 🐛 [Bug] Wrong graveyard when config patch below 1.12.1 when running 1.12.1 client.
## 🐛 Bug report

Player is still getting sent to graveyard even if graveyard doesn't exist on patch server is set to in config.
The graveyard you will be sent to will have no spirit healer.

Only works correctly if you are playing with correct client for the patch server is set to.

### Expected behavior

You should not get sent to a graveyard that doesn't exist for the client patch you set in config, even if you are playing on a different client version.

Raven Hill graveyard was added in 1.8.0

### Steps to reproduce

1. Die on patch 1.6.1 client near Raven Hill.
2. Get sent to Darkshire Graveyard.
WoW_1 6 1_BRTDxYwOtd
-------
1. Die on patch 1.12.1 client with 1.6.1 set in config while near Raven Hill.
2. Get sent to Raven Hill Graveyard but with no spirit healer.
WoW_qOM43F2nGO

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  https://github.com/vmangos/core/commit/373fde44b3c8c6f5236656e31dabffbb5f728037

OS Client: Microsoft Windows 11 Pro N 10.0.22000 Build 22000
OS Server: Microsoft Windows 11 Pro N 10.0.22000 Build 22000

### Crashlog

- None

### PR DESCRIPTION
**Pull request by Daribon**
## 🍰 Pullrequest

This PR changes build_min to patch_min and adds patch_max to game_graveyard_zone.
It will read patch set in mangosd.conf, so you will not be sent to a graveyard that is not for the set patch.
If you build vmangos for a patch below 1.12.1, it will still work just as before and use correct graveyards.

Includes SQL fixes for all graveyards that was changed from between 1.2 to 1.12.
### Proof

- Patch notes.

### Issues

- Fixes https://github.com/vmangos/core/issues/1590
- Fixes https://github.com/vmangos/core/issues/1492

### How2Test

1. Set patch 3 in mangosd.conf
2. .tele ravenhill
3. .die
4. You will now spawn at Darkshire graveyard.
5. Set patch 10 in mangosd.conf
6. .tele ravenhill
7. .die
8. You will spawn at Raven Hill graveyard.

### Todo / Checklist

- [X] Make Goldshire GY neutral in pre 1.6
- [X] Set patch in creature table for all spirit healers that weren't spawned in prior patch.
- [X] Find a way to use Orgrimmar Durotar GY for Hall of Legends when Razor Hill GY is set to neutral.
- [X] Fix graveyard for dying in Uldaman on old patch.

### CODE REVIEW

**Comment by FlagFlayer** [comment]
Would it be possible to add a fix to https://github.com/vmangos/core/issues/1492 in this PR as well?

**Comment by Daribon** [comment]
Yes, I will fix it as well.

**Comment by FlagFlayer** [comment]
For "Find a way to use Orgrimmar Durotar GY for Hall of Legends when Razor Hill GY is set to neutral." Would setting Razor Hill GY to be Alliance only for Hall of Legends work?

**Comment by Daribon** [comment]
No, since then horde players won't have a place to rez in Hall of Legends in pre 1.6.

A solution could be to add something like patch max and simply set Hall of Legends to use Razor Hill below 1.6 but Orgrimmar, durotar GY when above 1.6. 

The issue with Goldshire is that it used to be a neutral graveyard. If I change it to be neutral then it will be neutral as well in later patches. A patch max would solve this and then have two entries for the exact same graveyard, one for neutral and one for alliance only.

----
My current solution for Uldaman is the following:
```SQL
-- Set min patch for Badlands, Graveyard NE GY
UPDATE `game_graveyard_zone` SET `patch_min`='10' WHERE  `id`=8;
-- Add Badlands and Uldaman to Loch Modan, Thelsamar GY
INSERT INTO `game_graveyard_zone` (`id`, `ghost_zone`, `faction`, `patch_min`) VALUES ('6', '3', '0', '0');
INSERT INTO `game_graveyard_zone` (`id`, `ghost_zone`, `faction`, `patch_min`) VALUES ('6', '1337', '0', '0');
```

However I'm not certain if Uldaman and north Badlands used to have Thelsamar as graveyard.
It does seem very possible since Thelsamar is a neutral graveyard and is the closest.

**Comment by Daribon** [comment]
Fixed all issues.
Everything should now be working.

File: sql/migrations/20220925023354_world.sql [hunk 1]
```diff
@@ -0,0 +1,154 @@
...
+
+-- Set Feralas, Dire Maul GY to patch 1.6
+UPDATE `game_graveyard_zone` SET `patch_min`='4' WHERE  `id`=849;
+-- Set Feralas, Dire Maul GY Spirit Healer to patch 1.6
+UPDATE `creature` SET `patch_min`='4' WHERE  `guid`=40561;
+-- Use Feralas, Camp Mojache for Dire Maul GY pre patch 1.6
+INSERT INTO `game_graveyard_zone` (`id`, `ghost_zone`) VALUES ('310', '2557');
+
+-- Set The Hinterlands, The Overlook Cliffs GY to patch 1.6
+UPDATE `game_graveyard_zone` SET `patch_min`='3' WHERE  `id`=789 AND `ghost_zone`=47;
```
Comment (FlagFlayer) [inline sql/migrations/20220925023354_world.sql:106]: Isn't this supposed to be patch_min 4?

Comment (Daribon) [reply sql/migrations/20220925023354_world.sql:106]: I see that I commented it incorrectly as 1.6.0.
The graveyard was added in 1.5.0.
Fixed.

File: sql/migrations/20220925023354_world.sql [hunk 2]
```diff
@@ -0,0 +1,164 @@
...
+-- Set Elwynn Forest, Eastvale Logging Camp GY to patch 1.6
+UPDATE `game_graveyard_zone` SET `patch_min`='4' WHERE  `id`=854;
+-- Set Elwynn Forest, Eastvale Logging Camp GY Spirit Healer to patch 1.6
+UPDATE `creature` SET `patch_min`='4' WHERE  `guid`=17650;
+
+-- Set min patch for Badlands, Graveyard NE GY
+UPDATE `game_graveyard_zone` SET `patch_min`='10' WHERE  `id`=8;
+-- Add Badlands and Uldaman to Loch Modan, Thelsamar GY
+INSERT INTO `game_graveyard_zone` (`id`, `ghost_zone`, `faction`, `patch_min`) VALUES ('6', '3', '0', '0');
+INSERT INTO `game_graveyard_zone` (`id`, `ghost_zone`, `faction`, `patch_min`) VALUES ('6', '1337', '0', '0');
```
Comment (FlagFlayer) [inline sql/migrations/20220925023354_world.sql]: While Thelsamar makes a solid amount of sense as a graveyard for Uldaman berfore patch 1.12 (Similar to Twilight Vale, Darkshore for BFD), I seriously doubt it as a graveyard for the Badlands as a zone. It would be a very strange behaviour for it to be that way, since in every case I can think of if a zone has a graveyard it will not use graveyards from outside the zone for itself, and Badlands has a graveyard in Kargath.

Comment (Daribon) [reply sql/migrations/20220925023354_world.sql]: I've finally found evidence regarding the uldaman graveyard pre 1.12.0.
This video https://youtu.be/eHCZPBF3gAo?t=33 shows that the graveyard for Uldaman pre 1.12.0 should be in Kargath.

A screenshot from the video:
firefox_BLMcwx6slY
A screenshot from me on 1.12.1 after releasing spirit in uldaman:
WoW_B8H7t13HPr

It confirms that the video is a ghost run to the portal in pre 1.12.0.

The SQL will be updated to the correct graveyard later today.

**Comment by Daribon** [comment]
This is now fully working as intended.
It has been tested on Everlook by thousands of players for months, with the exception of the most recent fix to Uldaman above.

Ready for merge.

**Comment by FlagFlayer** [comment]
Once this finishes building https://github.com/vmangos/core/pull/1640 can also be merged: It has also been widely tested on Everlook, being merged together with this PR a few months back.
